# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - pandoc
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install: pip install tox

script: 
  - pandoc -v || True
  - tox

notifications:
  email: false
